### ISSUE TITLE
App not showing up on heroku 

### ISSUE THREAD

**Issue by KVanSant** [KVanSant/brunch-and-booze#14]
I though we were done with heroku issues, but apparently not. Just pushed to heroku and it's showing  {"statusCode":404,"error":"Not Found"} . I though we figured out how to fix this when working on another app but I can't remember. Any insight would be great. I can keep working locally, so this is not a huge issue, but still something that needs to be fixed. I'll continue to try and figure it out as well.

**Comment by ghost** [comment]
@KVanSant Hrm, yes, that is strange, and I do recall it happening before. Were you pushing successfully before or was this the first push to Heroku? I'm guessing the first push, but for some reason I thought it had been pushed before. In any case, after you pushed to Heroku did the terminal output throw any errors? Or did it look clean? Inspect the page at the Heroku URL and check the Network (reload the page after you're on the Network tab) to see if everything is a 404 or just the index.html page. We can further troubleshoot today as well.

**Comment by ghost** [comment]
@KVanSant I spent ~15 mins browsing through old messages on Bloc to see if I could find the previous instance of this related issue but I didn't find anything. :-/ But if we solved it before then we can solve it again.

**Comment by KVanSant** [comment]
@clln We've pushed this to Heroku before at the very early stages, but I don't think I checked to make sure it worked then. That's what I get for assuming!  No blatant errors were thrown but a few warnings.  

![](https://lh4.googleusercontent.com/-MhwWPnq85AA/VRQ4Bq8duXI/AAAAAAAAPjk/MOQ-4XlCw68/w988-h270-no/Screen%2BShot%2B2015-03-26%2Bat%2B9.29.45%2BAM.png)

![](https://lh4.googleusercontent.com/-iRUEaD9xy-g/VRQ4BgF5gkI/AAAAAAAAPj0/Frbjj7b9Byk/w970-h613-no/Screen%2BShot%2B2015-03-26%2Bat%2B9.32.11%2BAM.png)

![](https://lh5.googleusercontent.com/-PEZOlFvzjwg/VRQ4CHkHhKI/AAAAAAAAPjw/5vnHZBNC02A/w828-h991-no/Screen%2BShot%2B2015-03-26%2Bat%2B9.33.12%2BAM.png)

Hope those help....

**Comment by KVanSant** [comment]
@clln So I just fixed the heroku issue! Haha. I removed dist/ from gitignore. Then pushed to heroku and it worked. Then I added dist/ back in and pushed to heroku, and it still works. Voila!  If you could try it out for yourself to make sure it works for you! I updated the heroku link above the repo.

**Comment by ghost** [comment]
@KVanSant lololol, so we _had_ uncovered the issue in investigating your Bloc Chat repo!!! The `dist/` directory was the key!! I'm still going to get a follow up on the base frontend project and see if it's an issue that has been brought up by other students...

Nice investigative work!!

**Comment by KVanSant** [comment]
@clln Thanks! Yeah if you do follow up let me know cause I'm really curious if others have had a problem....or if it's just me. ;) And now we have it documented in case any future students.....or myself....have issues with it again!
